api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: "API FINGZ"
    version: "0.0.1"
    collection:
        order_parameter_name: "order"
        pagination:
            page_parameter_name: "page"
            items_per_page_parameter_name: "itemsPerPage"
            client_items_per_page: true
    defaults:
        pagination_items_per_page: 100000 # Default value
    #eager_loading:
        #max_joins: 100